# config/packages/translation.yaml
framework:
    default_locale: 'sr'
    # U Symfony 6.4 se lista dozvoljenih jezika piše OVDE:
    enabled_locales: ['sr', 'en']
    
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'en'